imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@RemiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.book_images: /images/book

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


vich_uploader:
    db_driver: orm
    mappings:
        book_images:
            uri_prefix:         %app.path.book_images%
            upload_destination: %kernel.root_dir%/../web/images/book
            namer:              vich_uploader.namer_uniqid

easy_admin:
    site_name: 'Remi Back-Office'
    design:
        menu:
            - { entity: 'BookPhoto' }
        form_theme:   'vertical'
    list:
        actions:
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'delete'}
    formats:
        date: 'd/m/Y'
    entities:
        BookPhoto:
            class: RemiBundle\Entity\BookPhoto
            label: 'Book Photo'
            form:
                title: 'Ajouter une photo'
                fields:
                    - { property: 'imageFile', type: 'file' }
                    - { property: 'enabled', label: Afficher }
            list:
                title: 'Book Photo'
                actions:
                    - { name: 'edit', label: 'Modifier', icon: 'edit' }
                    - { name: 'delete', label: 'Supprimer', icon: 'trash' }
                fields:
                    - { property: 'image', type: 'image', base_path: %app.path.book_images% }
                    - { property: 'enabled', label: Afficher }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: %app.path.book_images% }


